### ISSUE TITLE
Building a full-stack application with Effect

### ISSUE THREAD

**Issue by wewelll** [evryg-org/effect-paris#1]
### Format

Long (20 minutes)

### Description

In this talk, I will show how to build a full-stack application using libraries from the Effect ecosystem.

The plan is : 

- Domain modeling using `@effect/schema`
- HTTP server using `@effect/platform`
- HTTP client using `@effect/platform`
- API design with [`effect-http`](https://github.com/sukovanej/effect-http)
  - sharing API schema between server and client
  - OpenAPI specs generation

### Twitter

https://x.com/SamuelBriole

### Email

sb@spiko.tech

**Comment by antoine-coulon** [comment]
Hello @wewelll :) 

Are you available for the next edition taking place on 25th of June?

**Comment by wewelll** [comment]
Yes absolutely ! :)

**Comment by antoine-coulon** [comment]
Perfect, see you the 25th then!

**Comment by antoine-coulon** [comment]
The talk was done on June 25th, thanks again @wewelll ! Slides will be added to the repository
