### ISSUE TITLE
Effect dans la pratique : Adoption et impacts dans une équipe sans expérience préalable avec la librairie

### ISSUE THREAD

**Issue by Mathieuka** [evryg-org/effect-paris#2]
### Format

Long (20 minutes)

### Description

Explorez notre parcours d'intégration de la bibliothèque Effect par une équipe sans expérience préalable avec ce paradigme, les défis relevés et les améliorations concrètes obtenues en termes de qualité du code et répercutions sur les utilisateurs.

### Email

mathieu.kahlaoui.pro@gmail.com

**Comment by antoine-coulon** [comment]
Salut @Mathieuka, c'est parti pour la prochaine édition le 25 juin ;)

**Comment by antoine-coulon** [comment]
Le talk a été effectué le 25 juin, encore merci @Mathieuka ! Le contenu des slides sera ajouté au repository
