### ISSUE TITLE
Domain modeling with `effect/Schema`

### ISSUE THREAD

**Issue by oscarwroche** [evryg-org/effect-paris#5]
### Format

Long (20 minutes)

### Description

How to model domain logic using `effect/Schema` features:

- Introduction to `effect/Schema`
- Union types / union schemas to model domain entity lifecycles
- Schema classes to colocate domain schemas and data types
- Bonus: How to generate entities for testing (among others) using `Arbitrary`

This is inspired by the famous [Domain modeling made functional](https://www.youtube.com/watch?v=Up7LcbGZFuo) book / talks by Scott Wlaschin.

### Email

or@spiko.tech

**Comment by oscarwroche** [comment]
I could do the presentation on November 5th if it's OK :)

**Comment by antoine-coulon** [comment]
Hello @oscarwroche, thanks for submitting the talk :) 

Perfect then let's plan it for the 5th!
